# Generated by Django 4.1.7 on 2023-10-11 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_salesitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Udhaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('mobile', models.IntegerField(default=0)),
                ('transaction_code', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('payment', models.IntegerField(default=0)),
                ('udhaar', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='amount_change',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='code',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tendered_amount',
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
