# Generated by Django 4.1.7 on 2023-10-11 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_udhaar_remove_products_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sales',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='disc_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='discount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='grand_total',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='mobile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='payment',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='sub_total',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='udhaar',
            field=models.FloatField(default=0, null=True),
        ),
    ]
