# Generated by Django 4.1.7 on 2023-10-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='kg_price',
        ),
        migrations.AddField(
            model_name='products',
            name='m_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
