# Generated by Django 4.1.7 on 2023-10-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_rename_price_products_kg_price_products_m_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='scale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
