# Generated by Django 4.1.7 on 2023-10-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_salesitems_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='m_price',
        ),
        migrations.AddField(
            model_name='products',
            name='scale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
