# Generated by Django 4.1.7 on 2023-10-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_remove_products_m_price_products_scale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='kg_price',
            new_name='price',
        ),
    ]
