# Generated by Django 4.1.7 on 2023-10-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0011_rename_kg_price_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='discount',
        ),
    ]
